# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6400de13b646038780e0dd5c433f667b9b23cad222317666b150e24d3b6af9239fe11fe0042009b84f35206a8dce641e8a5c59b51b7bab5bf1fd6f2a51cf2e7c

test:
  secret_key_base: 33f795dd996975ed80e282f6170c898e216625e260c32f40353c32143aa40c0f0005c2282c04ff30d929dbd122072746a4acc9896677a6611aea99cbd2c6599b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
